### ISSUE TITLE
Incorrect boolean value passed to clause of @Where annotation

### ISSUE THREAD

**Issue by btundes** [terasolunaorg/guideline#1525]
## Description
Incorrect boolean value passed to clause of  ``` @Where ```annotation while adding common conditions in JPQL to fetch entities
Guideline Location-
Entity specification at-
http://terasolunaorg.github.io/guideline/5.0.1.RELEASE/en/ArchitectureInDetail/DataAccessJpa.html#adding-common-conditions-in-jpql-to-fetch-entities

## Possible Solutions
The boolean value false should be enclosed in single quotes

Existing specification
```java
@Entity
@Table(name = "t_order")
@Where(clause = "is_logical_delete = false") // (1)
public class Order implements Serializable {
    // ...
    @Id
    private Integer id;
    // ...
}
```

Corrected specification
```java
@Entity
@Table(name = "t_order")
@Where(clause = "is_logical_delete = 'false' ") // (1)
public class Order implements Serializable {
    // ...
    @Id
    private Integer id;
    // ...
}
```

## Affects Version/s
- 5.0.1.RELEASE

## Fix Version/s
- [x] 5.1.0.RELEASE
- [x] 5.1.0.RELEASE_en
- [x] 5.0.2.RELEASE
- [x] 5.0.2.RELEASE_en

## Issue Links

**Comment by ikeyat** [comment]
The content of ``clause`` depends on DB implementation because ``clause`` is not JPQL but SQL.
But  some articles say ``Dialect`` transform ``clause`` to adaptable SQL for each DB implementation.

http://stackoverflow.com/questions/26800618/hibernate-where-clause-inconsistent-between-hsql-and-mysql 
http://stackoverflow.com/questions/10730640/is-there-a-way-to-stop-hibernate-from-corrupting-boolean-literals-in-where-anno 

@btundes 
Please reconsider the changes in this issue is correct or not.
Other possible solutions are
For example,
* Write ``clause`` with a specific DB expression
* Set dialect config (but some dialect class provided by Hibernate need to be fixed such as H2)

**Comment by ikeyat** [comment]
We tried dialect config but failed because that is a function for Hibernate to recognize DB specific reserved keywords in query. Oracle does not have ``true`` or ``false`` reserved keywords so this does not affect.

As a result, we need to fix guideline to write ``clase`` with DB specific query as following code.

```java
// for PostgreSQL
@Where(clause = "is_logical_delete = false")

// for Oracle
@Where(clause = "is_logical_delete = 0")
```

**Comment by ikeyat** [comment]
Please backport
