### ISSUE TITLE
Investigation of test coding guideline

### ISSUE THREAD

**Issue by ikeyat** [terasolunaorg/guideline#1817]
## Description
We need to consider to add test coding guideline. For example,
- Unit test coding with JUnit4+ and mock libraries
- Integration test coding with JUnit4+ and spring-test
- E2E test coding with JUnit4+ and Selenium

## Possible Solutions
Begin the investigation as internal task.

## Final Solutions
At 5.4.0 Support Unit test coding with JUnit4+ and mock libraries.

## Affects Version/s
N/A

## Fix Version/s
- [x] 5.4.0 (master)
- [x] 1.5.0 (m-j/master)
- [x] 1.5.0 (m-t/master)

## Change log(should be updated at the same time)
- [x] 5.4.0 (master)
- [x] 1.5.0 (m-j/master)
- [x] ~~1.5.0 (m-t/master)~~ not required.

## English Translation
- [ ] Required, create a new issue for handling

## Migrating Guide
- Not Required

## Issue Links
- #XXX

**Comment by itouyun** [comment]
Not JUnit4 but JUnit5 now?

**Comment by kazuki43zoo** [comment]
Following libraries are useful.

[Assertion support]
* [AssertJ](https://joel-costigliola.github.io/assertj/)

[Selenium support]
* [Selenide](http://selenide.org/)
* [webdrivermanager](https://github.com/bonigarcia/webdrivermanager)

**Comment by kazuki43zoo** [comment]
Other solutions are ...

* [Spock](https://github.com/spockframework/spock)
* [Geb](https://github.com/geb/geb)

Above solutions need to use the groovy language.

**Comment by kazuki43zoo** [comment]
JUnit 5 has been released on September 10, 2017!

http://junit.org/junit5/docs/current/user-guide/

**Comment by btkigamim** [comment]
We use DBUnit and sprint-test-dbunit to implement test of data access for the following reasons:

* Spring is an annotation-based framework.
  With sprint-test-dbunit, test processing（dataSetup, verification）can be written annotation based on Spring.
* Because test is described in annotation base, the amount of description of code decreases.
* spring-test-dbunit was made by Spring's commiter.
* Test library is used in development environment.

**Comment by yoshikawaa** [comment]
@hosoitk 
English translation remaining.
